"""
Comprehensive Unified Collection of All Serverless Computing Research Papers
==========================================================================

This file contains all papers from paper_list_1, paper_list_2, paper_list_3, and paper_list_4
combined into a single collection with standardized fields.

Total papers: 116

Fields included for each paper:
- unified_id: Unique sequential ID across all papers
- original_id: Original ID from source list
- title: Paper title
- authors: Paper authors
- year: Publication year
- venue: Publication venue/conference/journal
- category: Research category/area
- keywords: Keywords (string or list)
- pdf_link: Link to PDF
- doi: DOI identifier
- source_list: Which original list this paper came from
- metrics: Performance metrics (if available)
- abstract: Paper abstract (if available)
- notes: Additional notes (if available)
"""

# Comprehensive collection of all papers
papers = [
    {
        "unified_id": 1,
        "original_id": 1,
        "title": 'Cold Start Latency in Serverless Computing: A Systematic Review, Taxonomy, and Future Directions',
        "authors": 'Muhammed Golec et al.',
        "year": 2024,
        "venue": 'ACM Computing Surveys',
        "category": 'Performance, Latency',
        "keywords": 'cold start, survey, taxonomy',
        "pdf_link": 'https://arxiv.org/pdf/2310.08437',
        "doi": '10.1145/3700875',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 2,
        "original_id": 2,
        "title": 'The Night Shift: Understanding Performance Variability of Cloud Serverless Platforms',
        "authors": 'Trever Schirmer et al.',
        "year": 2023,
        "venue": "SESAME '23 Workshop (ACM)",
        "category": 'Performance, Variability',
        "keywords": 'performance variability, diurnal pattern, cold start',
        "pdf_link": 'https://arxiv.org/pdf/2304.07177',
        "doi": '10.1145/3592533.3592808',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 3,
        "original_id": 3,
        "title": 'SeBS: A Serverless Benchmark Suite for Function-as-a-Service Computing',
        "authors": 'Maciej Kopik et al.',
        "year": 2020,
        "venue": 'arXiv (Benchmarking Suite)',
        "category": 'Performance, Benchmarking',
        "keywords": 'benchmark suite, performance evaluation',
        "pdf_link": 'https://mcopik.github.io/files/TOSEM23_Serverless.pdf#page=51',
        "doi": 'arXiv:2006.00056',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 4,
        "original_id": 4,
        "title": 'Benchmarking, Analysis, and Optimization of Serverless Function Snapshots',
        "authors": 'Dmitrii Ustiugov et al.',
        "year": 2021,
        "venue": 'ASPLOS',
        "category": 'Performance, Startup',
        "keywords": 'snapshot, Firecracker, cold start',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3445814.3446700',
        "doi": '10.1145/3445814.3446700',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 5,
        "original_id": 5,
        "title": 'Catalyzer: Sub-millisecond Startup for Serverless Computing with Initialization-less Booting',
        "authors": 'Dong Du et al.',
        "year": 2020,
        "venue": 'ASPLOS',
        "category": 'Performance, Latency',
        "keywords": 'cold start, kernel, quick boot',
        "pdf_link": 'https://doi.org/10.1145/3373376.3378512',
        "doi": '10.1145/3373376.3378512',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 6,
        "original_id": 6,
        "title": 'Firecracker: Lightweight Virtualization for Serverless Applications',
        "authors": 'Alexandru Agache et al.',
        "year": 2020,
        "venue": 'USENIX NSDI',
        "category": 'Performance, Isolation',
        "keywords": 'microVM, isolation, startup time',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.5555/3387514.3405880',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 7,
        "original_id": 7,
        "title": 'SEUSS: Skip Redundant Paths to Make Serverless Fast',
        "authors": 'James Cadden et al.',
        "year": 2020,
        "venue": 'EuroSys',
        "category": 'Performance, Optimization',
        "keywords": 'optimizing platform, latency',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3342195.3387520',
        "doi": '10.1145/3342195.3387520',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 8,
        "original_id": 8,
        "title": 'From Warm to Hot Starts: Leveraging Runtimes for the Serverless Era',
        "authors": 'João Carreira et al.',
        "year": 2021,
        "venue": 'HotOS',
        "category": 'Performance, Cold Start',
        "keywords": 'runtime reuse, warm starts',
        "pdf_link": None,
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 9,
        "original_id": 9,
        "title": 'Peeking Behind the Curtains of Serverless Platforms',
        "authors": 'Liang Wang et al.',
        "year": 2018,
        "venue": 'USENIX ATC',
        "category": 'Performance, Measurement',
        "keywords": 'measurement study, AWS Lambda',
        "pdf_link": 'https://www.usenix.org/system/files/atc18-wang-liang.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 10,
        "original_id": 10,
        "title": 'Wukong: A Scalable and Locality-Enhanced Framework for Serverless Parallel Computing',
        "authors": 'Benjamin Carver et al.',
        "year": 2020,
        "venue": 'ACM SoCC',
        "category": 'Performance, Parallelism',
        "keywords": 'parallel computing, locality',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3419111.3421307',
        "doi": '10.1145/3419111.3421307',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 11,
        "original_id": 11,
        "title": 'Atoll: A Scalable Low-Latency Serverless Platform',
        "authors": 'Arjun Singhvi et al.',
        "year": 2021,
        "venue": 'ACM SoCC',
        "category": 'Performance, Latency',
        "keywords": 'platform design, low latency',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3472883.3486987',
        "doi": '10.1145/3472883.3486987',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 12,
        "original_id": 12,
        "title": 'FaaStLane: Accelerating Function-as-a-Service Workflows',
        "authors": 'Swaroop Kotni et al.',
        "year": 2021,
        "venue": 'USENIX ATC',
        "category": 'Performance, Workflow',
        "keywords": 'workflow, caching, DAG',
        "pdf_link": 'https://www.usenix.org/system/files/atc21-kotni.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 13,
        "original_id": 13,
        "title": 'SAND: Towards High-Performance Serverless Computing',
        "authors": 'Istemi E. Akkus et al.',
        "year": 2018,
        "venue": 'USENIX ATC',
        "category": 'Performance, Cold Start',
        "keywords": 'sandbox, warm pool',
        "pdf_link": 'https://www.usenix.org/system/files/atc18-akkus.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 14,
        "original_id": 14,
        "title": 'TinyFaaS: A Lightweight FaaS Platform for Edge Environments',
        "authors": 'Tobias Pfandzelter, David Bermbach',
        "year": 2020,
        "venue": 'IEEE Fog Computing',
        "category": 'Performance, Edge',
        "keywords": 'edge computing, lightweight FaaS',
        "pdf_link": 'https://ieeexplore.ieee.org/ielx7/9214522/9214523/09214560.pdf',
        "doi": '10.1109/ICFC49376.2020.00008',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 15,
        "original_id": 15,
        "title": 'Cold Start Latency Prediction Framework in Serverless Edge Computing',
        "authors": 'Sukhpal Singh Gill et al.',
        "year": 2024,
        "venue": 'IEEE JSAC',
        "category": 'Performance, Latency',
        "keywords": 'edge, cold start, prediction',
        "pdf_link": 'https://doi.org/10.1109/JSAC.2024.3396440',
        "doi": '10.1109/JSAC.2024.3396440',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 16,
        "original_id": 16,
        "title": 'Serverless in the Wild: Characterizing and Optimizing the Serverless Workload at a Large Cloud Provider',
        "authors": 'Mohammad Shahrad et al.',
        "year": 2020,
        "venue": 'USENIX ATC',
        "category": 'Reliability, Workload',
        "keywords": 'workload analysis, optimization',
        "pdf_link": 'https://www.usenix.org/system/files/atc20-shahrad.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 17,
        "original_id": 17,
        "title": 'Fault-tolerant and Transactional Stateful Serverless Workflows',
        "authors": 'Haoran Zhang et al.',
        "year": 2020,
        "venue": 'USENIX OSDI',
        "category": 'Reliability, Workflow',
        "keywords": 'fault tolerance, transactions, stateful',
        "pdf_link": 'https://www.usenix.org/system/files/osdi20-zhang_0.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 18,
        "original_id": 18,
        "title": 'CloudBurst: Stateful Functions-as-a-Service',
        "authors": 'Vikram Sreekanti et al.',
        "year": 2020,
        "venue": 'VLDB',
        "category": 'Reliability, Stateful',
        "keywords": 'stateful FaaS, storage',
        "pdf_link": 'http://www.vldb.org/pvldb/vol13/p2438-sreekanti.pdf',
        "doi": '10.14778/3407790.3407857',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 19,
        "original_id": 19,
        "title": 'A Fault-Tolerance Shim for Serverless Computing',
        "authors": 'Vikram Sreekanti et al.',
        "year": 2020,
        "venue": 'EuroSys',
        "category": 'Reliability',
        "keywords": 'fault tolerance, shim',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3342195.3387517',
        "doi": '10.1145/3342195.3387517',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 20,
        "original_id": 20,
        "title": 'OFC: An Opportunistic Caching System for FaaS Platforms',
        "authors": 'Djob Mvondo et al.',
        "year": 2021,
        "venue": 'EuroSys',
        "category": 'Reliability, Caching',
        "keywords": 'edge caching, FaaS',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3447786.3456245',
        "doi": '10.1145/3447786.3456245',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 21,
        "original_id": 21,
        "title": 'Valve: Securing Function Workflows on Serverless Computing Platforms',
        "authors": 'Pubali Datta et al.',
        "year": 2020,
        "venue": 'WWW Conference',
        "category": 'Security, Workflow',
        "keywords": 'security, workflow, data flow control',
        "pdf_link": 'https://arxiv.org/pdf/1911.02974',
        "doi": '10.1145/3366423.3380141',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 22,
        "original_id": 22,
        "title": 'S-FaaS: Trustworthy and Accountable Function-as-a-Service Using Intel SGX',
        "authors": 'Fritz Alder et al.',
        "year": 2019,
        "venue": 'ACM Cloud Security Workshop',
        "category": 'Security, Privacy',
        "keywords": 'SGX, confidentiality',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3338466.3358918',
        "doi": '10.1145/3338466.3358918',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 23,
        "original_id": 23,
        "title": 'Se-Lambda: Securing Privacy-Sensitive Serverless Applications Using SGX Enclave',
        "authors": 'Weizhong Qiang et al.',
        "year": 2018,
        "venue": 'SecureComm',
        "category": 'Security, Privacy',
        "keywords": 'SGX, enclave, privacy',
        "pdf_link": 'https://doi.org/10.1007/978-3-030-01704-0_22',
        "doi": '10.1007/978-3-030-01704-0_22',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 24,
        "original_id": 24,
        "title": 'Faasm: Lightweight Isolation for Efficient Stateful Serverless Computing',
        "authors": 'Simon Shillaker, Peter Pietzuch',
        "year": 2020,
        "venue": 'USENIX ATC',
        "category": 'Security, Isolation',
        "keywords": 'WebAssembly, isolation, stateful',
        "pdf_link": 'https://www.usenix.org/system/files/atc20-shillaker.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 25,
        "original_id": 25,
        "title": 'WLEC: A Not So Cold Architecture to Mitigate Cold Start Problem in Serverless Computing',
        "authors": 'Khondokar Solaiman et al.',
        "year": 2020,
        "venue": 'IEEE IC2E',
        "category": 'Security, Performance',
        "keywords": 'cold start, architecture',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9074090/9109250/09109263.pdf',
        "doi": '10.1109/IC2E48712.2020.00022',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 26,
        "original_id": 26,
        "title": 'Secure Serverless Computing Using Dynamic Information Flow Control',
        "authors": 'Kalev Alpernas et al.',
        "year": 2018,
        "venue": 'ACM OOPSLA',
        "category": 'Security, Model',
        "keywords": 'information flow, security model',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3276486',
        "doi": '10.1145/3276486',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 27,
        "original_id": 27,
        "title": 'Workflow Integration Alleviates Identity and Access Management in Serverless Computing',
        "authors": 'Arnav Sankaran et al.',
        "year": 2020,
        "venue": 'ACSAC',
        "category": 'Security, IAM',
        "keywords": 'identity management, security',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3427228.3427258',
        "doi": '10.1145/3427228.3427258',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 28,
        "original_id": 28,
        "title": 'Sequoia: Enabling Quality-of-Service in Serverless Computing',
        "authors": 'Ali Tariq et al.',
        "year": 2020,
        "venue": 'ACM SoCC',
        "category": 'QoS, Scheduling',
        "keywords": 'QoS, scheduling, isolation',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3419111.3421296',
        "doi": '10.1145/3419111.3421296',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 29,
        "original_id": 29,
        "title": 'QoS Aware FaaS Platform',
        "authors": 'K.R. Sheshadri, J. Lakshmi',
        "year": 2021,
        "venue": 'IEEE/ACM CCGrid',
        "category": 'QoS, Scheduling',
        "keywords": 'QoS, FaaS scheduling',
        "pdf_link": 'https://doi.org/10.1109/CCGrid54584.2021.00010',
        "doi": '10.1109/CCGrid54584.2021.00010',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 30,
        "original_id": 30,
        "title": 'Cocoa: Cold Start Aware Capacity Planning for Function-as-a-Service Platforms',
        "authors": 'Alim Ul Gias, Giuliano Casale',
        "year": 2020,
        "venue": 'IEEE MASCOTS',
        "category": 'QoS, Performance',
        "keywords": 'capacity planning, cold start',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9265970/9275170/09275236.pdf',
        "doi": '10.1109/MASCOTS48990.2020.9285913',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 31,
        "original_id": 31,
        "title": 'Adaptive Function Launching Acceleration in Serverless Computing Platforms',
        "authors": 'Zhengjun Xu et al.',
        "year": 2019,
        "venue": 'IEEE ICPADS',
        "category": 'QoS, Performance',
        "keywords": 'pre-warm, scheduling',
        "pdf_link": 'https://doi.org/10.1109/ICPADS47876.2019.00016',
        "doi": '10.1109/ICPADS47876.2019.00016',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 32,
        "original_id": 32,
        "title": 'Caerus: NIMBLE Task Scheduling for Serverless Analytics',
        "authors": 'Hong Zhang et al.',
        "year": 2021,
        "venue": 'USENIX NSDI',
        "category": 'QoS, Scheduling',
        "keywords": 'analytics, scheduling, performance',
        "pdf_link": 'https://www.usenix.org/system/files/nsdi21-zhang-hong.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 33,
        "original_id": 33,
        "title": 'Kraken: Adaptive Container Provisioning for Deploying Dynamic DAGs in Serverless Platforms',
        "authors": 'V.M. Bhasi et al.',
        "year": 2021,
        "venue": 'ACM SoCC',
        "category": 'QoS, ResourceMgmt',
        "keywords": 'DAG, autoscaling',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3472883.3486984',
        "doi": '10.1145/3472883.3486984',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 34,
        "original_id": 34,
        "title": 'Spock: Exploiting Serverless Functions for SLO and Cost Aware Resource Procurement',
        "authors": 'J.R. Gunasekaran et al.',
        "year": 2019,
        "venue": 'IEEE CLOUD',
        "category": 'QoS, Cost',
        "keywords": 'SLO, cost optimization',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/8786473/8796240/08796280.pdf',
        "doi": '10.1109/CLOUD.2019.00045',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 35,
        "original_id": 35,
        "title": 'Defuse: A Dependency-Guided Function Scheduler to Mitigate Cold Starts on FaaS Platforms',
        "authors": 'Jiacheng Shen et al.',
        "year": 2021,
        "venue": 'IEEE ICDCS',
        "category": 'QoS, Performance',
        "keywords": 'scheduler, cold start',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9471287/9471353/09471418.pdf',
        "doi": '10.1109/ICDCS51616.2021.00027',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 36,
        "original_id": 36,
        "title": 'Modeling and Optimization of Performance and Cost of Serverless Applications',
        "authors": 'Changyuan Lin, Hamzeh Khazaei',
        "year": 2020,
        "venue": 'IEEE TPDS',
        "category": 'Cost, Performance',
        "keywords": 'performance-cost model',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/5962385/8896416/08996429.pdf',
        "doi": '10.1109/TPDS.2020.3009173',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 37,
        "original_id": 37,
        "title": 'Costless: Optimizing Cost of Serverless Computing through Function Fusion and Placement',
        "authors": 'Tarek Elgamal',
        "year": 2018,
        "venue": 'IEEE/ACM SEC',
        "category": 'Cost, Performance',
        "keywords": 'cost optimization, fusion',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/8477147/8477154/08477164.pdf',
        "doi": '10.1109/SEC.2018.00012',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 38,
        "original_id": 38,
        "title": 'Be Wary of the Economics of "Serverless" Cloud Computing',
        "authors": 'Adam Eivy, Joe Weinman',
        "year": 2017,
        "venue": 'IEEE Cloud Computing',
        "category": 'Cost',
        "keywords": 'economics, pricing',
        "pdf_link": None,
        "doi": '10.1109/MCC.2017.18',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 39,
        "original_id": 39,
        "title": 'Optimal Pricing for Serverless Computing',
        "authors": 'Kunal Mahajan et al.',
        "year": 2019,
        "venue": 'IEEE GLOBECOM',
        "category": 'Cost, Theory',
        "keywords": 'pricing model, economics',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9013441/9014514/09014598.pdf',
        "doi": '10.1109/GLOBECOM38437.2019.9014074',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 40,
        "original_id": 40,
        "title": 'Cost-Aware Migration to Functions-as-a-Service Architecture',
        "authors": 'Adam Stafford et al.',
        "year": 2021,
        "venue": 'ECSA Workshops',
        "category": 'Cost, Migration',
        "keywords": 'refactoring, cost analysis',
        "pdf_link": 'https://link.springer.com/content/pdf/10.1007/978-3-030-85936-7_3.pdf',
        "doi": '10.1007/978-3-030-85936-7_3',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 41,
        "original_id": 41,
        "title": 'Predicting Performance and Cost of Serverless Functions with SAAF',
        "authors": 'Robert Cordingly et al.',
        "year": 2020,
        "venue": 'IEEE DASC',
        "category": 'Cost, Performance',
        "keywords": 'performance prediction, cost model',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9276233/9287080/09287327.pdf',
        "doi": '10.1109/DASC-PICom-CBDCom-CyberSciTech49142.2020.00112',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 42,
        "original_id": 42,
        "title": 'FaaSNet: Scalable and Fast Provisioning of Custom Serverless Container Runtimes',
        "authors": 'Ao Wang et al.',
        "year": 2021,
        "venue": 'USENIX ATC',
        "category": 'Cost, Performance',
        "keywords": 'provisioning, startup, cost',
        "pdf_link": 'https://www.usenix.org/system/files/atc21-wang-ao.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 43,
        "original_id": 43,
        "title": 'CSPOT: Portable, Multi-Scale FaaS for IoT',
        "authors": 'Rich Wolski et al.',
        "year": 2019,
        "venue": 'ACM/IEEE SEC',
        "category": 'Cost, ResourceMgmt',
        "keywords": 'IoT, edge, cost',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3318216.3363309',
        "doi": '10.1145/3318216.3363309',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 44,
        "original_id": 44,
        "title": 'Reducing Environmental Impact with Sustainable Serverless Computing',
        "authors": 'Mohammed Akour, Mamdouh Alenezi',
        "year": 2025,
        "venue": 'MDPI Sustainability',
        "category": 'Energy, Sustainability',
        "keywords": 'energy efficiency, green IT',
        "pdf_link": 'https://www.mdpi.com/2071-1050/17/7/2999/pdf',
        "doi": '10.3390/su17072999',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 45,
        "original_id": 45,
        "title": 'On the Power Consumption of Serverless Functions: An Evaluation of OpenFaaS',
        "authors": 'Abdulaziz Alhindi et al.',
        "year": 2022,
        "venue": 'CIFS Workshop',
        "category": 'Energy, Performance',
        "keywords": 'power consumption, OpenFaaS',
        "pdf_link": 'https://eprints.whiterose.ac.uk/193714/1/cifs2022-final.pdf',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 46,
        "original_id": 46,
        "title": 'RAEF: Energy-efficient Resource Allocation through Energy Fungibility in Serverless',
        "authors": 'Xuechao Jia, Laiping Zhao',
        "year": 2021,
        "venue": 'IEEE ICPADS',
        "category": 'Energy, ResourceMgmt',
        "keywords": 'energy allocation, RL scheduler',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9669527/9669562/09669590.pdf',
        "doi": '10.1109/ICPADS53394.2021.00060',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 47,
        "original_id": 47,
        "title": 'Integrating Energy Consumption in the Development of Serverless Applications',
        "authors": 'Frank Scheuner et al.',
        "year": 2023,
        "venue": 'Journal of Systems Architecture',
        "category": 'Energy, Tooling',
        "keywords": 'energy monitoring, development',
        "pdf_link": None,
        "doi": '10.1016/j.sysarc.2023.102879',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 48,
        "original_id": 48,
        "title": 'Harvesting Idle Resources for Accelerating Serverless Computing',
        "authors": 'Hanfei Yu et al.',
        "year": 2022,
        "venue": 'The Web Conference (WWW)',
        "category": 'Energy, Performance',
        "keywords": 'idle resources, energy reuse',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3485447.3512030',
        "doi": '10.1145/3485447.3512030',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 49,
        "original_id": 49,
        "title": 'A Holistic View on Resource Management in Serverless Computing Environments: Taxonomy and Future Directions',
        "authors": 'Anupama Mampage et al.',
        "year": 2021,
        "venue": 'ACM Computing Surveys',
        "category": 'ResourceMgmt, Survey',
        "keywords": 'resource management, taxonomy',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3472747',
        "doi": '10.1145/3472747',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 50,
        "original_id": 50,
        "title": 'Serverless Computing: State-of-the-Art, Challenges and Opportunities',
        "authors": 'Yongkang Li et al.',
        "year": 2022,
        "venue": 'IEEE TSC (Early Access)',
        "category": 'ResourceMgmt, Survey',
        "keywords": 'survey, resource challenges',
        "pdf_link": 'https://doi.org/10.1109/TSC.2022.3142269',
        "doi": '10.1109/TSC.2022.3142269',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 51,
        "original_id": 51,
        "title": 'Scheduling Methods to Reduce Response Latency of Function as a Service',
        "authors": 'P. Żuk, K. Rzadca',
        "year": 2020,
        "venue": 'IEEE SBAC-PAD',
        "category": 'ResourceMgmt, Performance',
        "keywords": 'scheduling, latency',
        "pdf_link": 'https://doi.org/10.1109/SBAC-PAD49847.2020.00024',
        "doi": '10.1109/SBAC-PAD49847.2020.00024',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 52,
        "original_id": 52,
        "title": 'DistributedFaaS: Execution of Containerized Serverless Applications in Multi-Cloud Infrastructures',
        "authors": 'Adbys Vasconcelos et al.',
        "year": 2019,
        "venue": 'Proc. 9th CLOSER',
        "category": 'ResourceMgmt, Multi-cloud',
        "keywords": 'multi-cloud, scheduling',
        "pdf_link": 'https://www.scitepress.org/Papers/2019/77633/77633.pdf',
        "doi": '10.5220/0007763301660173',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 53,
        "original_id": 53,
        "title": 'Adaptive Container Provisioning for Serverless Workflows (SFL Compiler)',
        "authors": 'Lukas Brand, Markus Mock',
        "year": 2021,
        "venue": "WoSC '21",
        "category": 'ResourceMgmt, Performance',
        "keywords": 'workflow, stateful functions',
        "pdf_link": None,
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 54,
        "original_id": 54,
        "title": 'FunctionBench: A Suite of Workloads for Serverless Cloud Function Service',
        "authors": 'Jeongchul Kim, Kyungyong Lee',
        "year": 2019,
        "venue": 'IEEE CLOUD',
        "category": 'ResourceMgmt, Benchmarking',
        "keywords": 'workloads, benchmark',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/8786473/8796240/08796246.pdf',
        "doi": '10.1109/CLOUD.2019.00039',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 55,
        "original_id": 55,
        "title": 'Sizeless: Predicting the Optimal Size of Serverless Functions',
        "authors": 'Simon Eismann et al.',
        "year": 2021,
        "venue": 'ACM Middleware',
        "category": 'ResourceMgmt, Performance',
        "keywords": 'autoscaling, memory sizing',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3464298.3493395',
        "doi": '10.1145/3464298.3493395',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 56,
        "original_id": 56,
        "title": 'Resource Management for Cloud Functions with Memory Tracing, Profiling and Autotuning',
        "authors": 'Josef Spillner',
        "year": 2020,
        "venue": '6th Intl. Workshop on Serverless Computing',
        "category": 'ResourceMgmt, Performance',
        "keywords": 'memory tuning, profiling',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.1145/3429880.3430106',
        "doi": '10.1145/3429880.3430106',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 57,
        "original_id": 57,
        "title": 'EMARS: Efficient Management and Allocation of Resources in Serverless',
        "authors": 'Aakanksha Saha, Sonika Jindal',
        "year": 2018,
        "venue": 'IEEE CLOUD',
        "category": 'ResourceMgmt',
        "keywords": 'resource allocation, FaaS',
        "pdf_link": None,
        "doi": '10.1109/CLOUD.2018.00140',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 58,
        "original_id": 58,
        "title": 'Skedulix: Hybrid Cloud Scheduling for Cost-Efficient Serverless Execution',
        "authors": 'Anirban Das et al.',
        "year": 2020,
        "venue": 'IEEE CLOUD',
        "category": 'ResourceMgmt, Cost',
        "keywords": 'hybrid cloud, scheduling',
        "pdf_link": 'https://ieeexplore.ieee.org/iel7/9273268/9276606/09276647.pdf',
        "doi": '10.1109/CLOUD49709.2020.00031',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 59,
        "original_id": 59,
        "title": 'Optimizing Serverless Computing: Introducing an Adaptive Function Placement Algorithm',
        "authors": 'Nima Mahmoudi et al.',
        "year": 2019,
        "venue": 'CASCON',
        "category": 'ResourceMgmt, Performance',
        "keywords": 'function placement, edge vs cloud',
        "pdf_link": 'https://dl.acm.org/doi/pdf/10.5555/3377167.3377189',
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 60,
        "original_id": 60,
        "title": 'AuctionWhisk: Auction-Inspired Approach for Function Placement in Serverless Fog Platforms',
        "authors": 'David Bermbach et al.',
        "year": 2022,
        "venue": 'Software: Practice & Experience',
        "category": 'ResourceMgmt, Scheduling',
        "keywords": 'fog computing, auction scheduling',
        "pdf_link": 'https://doi.org/10.1002/spe.3032',
        "doi": '10.1002/spe.3032',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 61,
        "original_id": 61,
        "title": 'Comparison of FaaS Platform Performance in Private Clouds',
        "authors": 'Marcelo A. C. Motta et al.',
        "year": 2022,
        "venue": 'Proc. 12th CLOSER (SciTePress)',
        "category": 'Performance, Benchmarking',
        "keywords": 'OpenFaaS, OpenWhisk, private cloud',
        "pdf_link": 'https://www.scitepress.org/Papers/2022/111167/111167.pdf',
        "doi": '10.5220/0011116700001060',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 62,
        "original_id": 62,
        "title": 'ElastiBench: Scalable Continuous Benchmarking on Cloud FaaS Platforms',
        "authors": 'Trever Schirmer et al.',
        "year": 2024,
        "venue": 'IEEE IC2E (arXiv preprint)',
        "category": 'Benchmarking, Performance',
        "keywords": 'continuous benchmarking, scalability',
        "pdf_link": 'https://arxiv.org/pdf/2405.13528',
        "doi": 'arXiv:2405.13528',
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 63,
        "original_id": 63,
        "title": 'Performance Evaluation of Serverless Applications and Infrastructures',
        "authors": 'Joel Scheuner',
        "year": 2022,
        "venue": 'PhD Thesis (Chalmers)',
        "category": 'Performance, Benchmarking',
        "keywords": 'benchmark survey, reproducibility',
        "pdf_link": None,
        "doi": None,
        "source_list": 'paper_list_1',
        "metrics": '',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 64,
        "original_id": '',
        "title": 'RL-Based Approach to Enhance Reliability and Efficiency in Autoscaling for Heterogeneous Edge Serverless Computing Environments',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Reliability, Performance',
        "keywords": ['reliability', 'efficiency', 'autoscaling', 'edge computing', 'latency', 'resource management'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10858932/',
        "doi": '10.1109/...',
        "source_list": 'paper_list_2',
        "metrics": '25% latency reduction, 40% throughput increase',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 65,
        "original_id": '',
        "title": 'Optimizing Cold Start Performance in Serverless Computing Environments',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Latency, Performance',
        "keywords": ['cold start', 'latency', 'performance', 'reliability'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10896391/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '7x response time reduction',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 66,
        "original_id": '',
        "title": 'A Low-Latency Edge-Cloud Serverless Computing Framework with a Multi-Armed Bandit Scheduler',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Latency, Resource Management',
        "keywords": ['low-latency', 'edge-cloud', 'scheduling', 'multi-armed bandit'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10592558/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Minimal latency compared to single-tier systems',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 67,
        "original_id": '',
        "title": 'FUYAO: DPU-enabled Direct Data Transfer for Serverless Computing',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'ACM',
        "category": 'Latency, Performance',
        "keywords": ['data transfer', 'latency', 'DPU', 'performance'],
        "pdf_link": 'https://dl.acm.org/doi/10.1145/3620666.3651327',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Up to 57x latency improvement',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 68,
        "original_id": '',
        "title": 'Tackling Cold Start in Serverless Computing with Multi-Level Container Reuse',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Latency, Resource Management',
        "keywords": ['cold start', 'container reuse', 'resource management'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10579145/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '53% reduction in startup latency',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 69,
        "original_id": '',
        "title": 'FIAless: Asynchronous Programming for Large-Scale Burst Requests in Serverless Computing',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Performance, Resource Management',
        "keywords": ['asynchronous programming', 'burst requests', 'performance', 'resource management'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/11083138/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '61% request execution time reduction, 80% memory reduction',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 70,
        "original_id": '',
        "title": 'KneeScale: Efficient Resource Scaling for Serverless Computing at the Edge',
        "authors": 'Not specified',
        "year": '2022',
        "venue": 'IEEE',
        "category": 'Resource Management, Performance',
        "keywords": ['resource scaling', 'edge computing', 'auto-scaling'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/9826051/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '32% and 106% performance improvement over competitors',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 71,
        "original_id": '',
        "title": 'Towards Quality of Experience Fairness for Serverless Functions',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'QoS, Resource Management',
        "keywords": ['QoS', 'fairness', 'resource allocation'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10631094/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '89% and 85% QoE fairness improvement',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 72,
        "original_id": '',
        "title": 'Enabling HPC Scientific Workflows for Serverless',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Resource Management, Performance',
        "keywords": ['HPC', 'scientific workflows', 'resource management'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10820688/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '78.11% CPU and 73.92% memory usage reduction',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 73,
        "original_id": '',
        "title": 'Optimizing Resource Management in Serverless Computing: A Dynamic Adaptive Scaling Approach',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Resource Management, Cost',
        "keywords": ['dynamic scaling', 'resource management', 'cost optimization'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10724128/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": '30% resource utilization improvement, 25% cost reduction',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 74,
        "original_id": '',
        "title": 'ATOM: AI-Powered Sustainable Resource Management for Serverless Edge Computing Environments',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Resource Management, Energy Consumption',
        "keywords": ['AI', 'sustainable computing', 'edge computing', 'energy efficiency'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10376318/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Energy consumption and CO2 emission evaluation',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 75,
        "original_id": '',
        "title": 'Resource Management in Serverless Computing - Review, Research Challenges, and Prospects',
        "authors": 'Not specified',
        "year": '2023',
        "venue": 'IEEE',
        "category": 'Resource Management, Survey',
        "keywords": ['resource management', 'survey', 'QoS'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10249574/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Survey paper - no specific metrics',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 76,
        "original_id": '',
        "title": 'Joint Resource Management and Pricing for Task Offloading in Serverless Edge Computing',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Resource Management, Cost',
        "keywords": ['resource allocation', 'pricing', 'edge computing', 'energy efficiency'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10329995/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Order of magnitude improvement in revenue and energy savings',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 77,
        "original_id": '',
        "title": 'Serverless Edge Computing Framework for Efficient Offloading Method with Time Frame Based Priority Resource Management',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'IEEE',
        "category": 'Resource Management, Latency',
        "keywords": ['edge computing', 'offloading', 'resource management', 'latency'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10625440/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Reduced latency performance',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 78,
        "original_id": '',
        "title": 'Toward security quantification of serverless computing',
        "authors": 'Not specified',
        "year": '2024',
        "venue": 'Springer',
        "category": 'Security, Privacy',
        "keywords": ['security quantification', 'attack tree', 'privacy'],
        "pdf_link": 'https://journalofcloudcomputing.springeropen.com/articles/10.1186/s13677-024-00703-y',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Security risk quantification methodology',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 79,
        "original_id": '',
        "title": 'A Performance Benchmark for Serverless Function Triggers',
        "authors": 'Joel Scheuner',
        "year": '2022',
        "venue": 'IEEE IC2E',
        "category": 'Performance, Benchmarking',
        "keywords": ['performance benchmark', 'function triggers', 'distributed tracing'],
        "pdf_link": 'https://joelscheuner.com/publication/scheuner-22-ic2e/scheuner-22-ic2e.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Trigger latency measurements across providers',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 80,
        "original_id": '',
        "title": 'Designing Quality of Service aware Serverless Platforms',
        "authors": 'Sheshadri Kalkunte Ramachandra',
        "year": '2024',
        "venue": 'IISc Thesis',
        "category": 'QoS',
        "keywords": ['QoS', 'serverless platforms', 'resource allocation'],
        "pdf_link": 'https://etd.iisc.ac.in/handle/2005/6728',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'QoS-aware resource management',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 81,
        "original_id": '',
        "title": 'ENERGY-EFFICIENT AND COST-EFFECTIVE SERVERLESS COMPUTING',
        "authors": 'Neetu Gangwani',
        "year": '2024',
        "venue": 'IJRCAIT',
        "category": 'Energy Consumption, Cost',
        "keywords": ['energy efficiency', 'cost effectiveness', 'green computing'],
        "pdf_link": 'https://iaeme.com/MasterAdmin/Journal_uploads/IJRCAIT/VOLUME_7_ISSUE_2/IJRCAIT_07_02_049.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Energy efficiency analysis',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 82,
        "original_id": '',
        "title": 'Practical Cloud Workloads for Serverless FaaS',
        "authors": 'Not specified',
        "year": '2019',
        "venue": 'ACM',
        "category": 'Benchmarking',
        "keywords": ['workloads', 'FaaS', 'benchmarking', 'evaluation'],
        "pdf_link": 'https://dl.acm.org/doi/10.1145/3357223.3365439',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'FunctionBench benchmark suite',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 83,
        "original_id": '',
        "title": 'Analyzing Tail Latency in Serverless Clouds with STeLLAR',
        "authors": 'Not specified',
        "year": '2021',
        "venue": 'IEEE',
        "category": 'Latency, Benchmarking',
        "keywords": ['tail latency', 'performance characterization', 'benchmarking'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/9668286/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Tail latency analysis framework',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 84,
        "original_id": '',
        "title": 'Benchmarking Serverless Computing Platforms',
        "authors": 'Martins Horácio, Araujo Filipe, da Cunha Paulo Rupino',
        "year": '2020',
        "venue": 'Springer',
        "category": 'Benchmarking',
        "keywords": ['benchmarking', 'performance evaluation', 'cloud platforms'],
        "pdf_link": 'https://link.springer.com/article/10.1007/s10723-020-09523-1',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Cross-platform benchmark suite',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 85,
        "original_id": '',
        "title": "Performance Evaluation Of Amazon's, Google's, And Microsoft's Serverless Functions: A Comparative Study",
        "authors": 'Fahim Uz Zaman, Abdul Hafeez Khan, Muhammad Owais',
        "year": '2021',
        "venue": 'IJSTR',
        "category": 'Performance, Benchmarking',
        "keywords": ['AWS Lambda', 'Google Cloud Functions', 'Azure Functions', 'performance comparison'],
        "pdf_link": 'https://www.ijstr.org/final-print/apr2021/Performance-Evaluation-Of-Amazons-Googles-And-Microsofts-Serverless-Functions-A-Comparative-Study.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Cross-platform performance evaluation',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 86,
        "original_id": '',
        "title": 'Evaluating Serverless Function Deployment Models on AWS Lambda',
        "authors": 'Gabriel Duessmann, Adriano Fiorese',
        "year": '2025',
        "venue": 'SCITEPRESS',
        "category": 'Performance, Cost',
        "keywords": ['deployment models', 'AWS Lambda', 'performance', 'cost'],
        "pdf_link": 'https://www.scitepress.org/Papers/2025/132795/132795.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Container image vs ZIP deployment comparison',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 87,
        "original_id": '',
        "title": 'Function-as-a-Service Benchmarking Framework',
        "authors": 'Roland Pellegrini, Igor Ivkic, Markus Tauber',
        "year": '2019',
        "venue": 'SCITEPRESS',
        "category": 'Benchmarking',
        "keywords": ['benchmarking framework', 'FaaS', 'performance evaluation'],
        "pdf_link": 'https://www.scitepress.org/Papers/2019/77573/77573.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'FaaS benchmarking tool architecture',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 88,
        "original_id": '',
        "title": 'Serverless Computing & Function-as-a-Service (FaaS) Optimization',
        "authors": 'Nishanth Reddy Pinnapareddy',
        "year": '2023',
        "venue": 'TAJET',
        "category": 'Performance, Security',
        "keywords": ['FaaS optimization', 'cold start', 'security', 'multi-cloud'],
        "pdf_link": 'https://theamericanjournals.com/index.php/tajet/article/view/6037',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Platform comparison and optimization',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 89,
        "original_id": '',
        "title": 'Rise of the Planet of Serverless Computing: A Systematic Review',
        "authors": 'Not specified',
        "year": '2022',
        "venue": 'arXiv',
        "category": 'Survey',
        "keywords": ['systematic review', 'serverless computing', 'performance optimization'],
        "pdf_link": 'https://arxiv.org/pdf/2206.12275.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Review of 164 papers on serverless computing',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 90,
        "original_id": '',
        "title": 'Towards Seamless Serverless Computing Across an Edge-Cloud Continuum',
        "authors": 'Emilian Simion, Yuandou Wang, Hsiang-ling Tai, Uraz Odyurt, Zhiming Zhao',
        "year": '2024',
        "venue": 'arXiv',
        "category": 'Edge Computing',
        "keywords": ['edge-cloud', 'orchestration', 'serverless deployment'],
        "pdf_link": 'https://arxiv.org/abs/2401.02271',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Performance benefits of edge-cloud deployment',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 91,
        "original_id": '',
        "title": 'An Application-Centric Benchmarking Framework for FaaS Platforms',
        "authors": 'Martin Grambow, Tobias Pfandzelter, Luk Burchard, Carsten Schubert, Max Zhao, David Bermbach',
        "year": '2021',
        "venue": 'arXiv',
        "category": 'Benchmarking',
        "keywords": ['application-centric', 'benchmarking', 'FaaS platforms'],
        "pdf_link": 'https://arxiv.org/pdf/2102.12770.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'BeFaaS benchmarking framework',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 92,
        "original_id": '',
        "title": 'Function-as-a-Service Performance Evaluation: A Multivocal Literature Review',
        "authors": 'Joel Scheuner, Philipp Leitner',
        "year": '2020',
        "venue": 'arXiv',
        "category": 'Survey, Performance',
        "keywords": ['performance evaluation', 'literature review', 'FaaS'],
        "pdf_link": 'https://arxiv.org/abs/2004.03276',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Review of 112 studies on FaaS performance',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 93,
        "original_id": '',
        "title": 'Survey on serverless computing: Performance evaluation & benchmarking',
        "authors": 'Paul Castro, Vatche Ishakian, Vinod Muthusamy, et al.',
        "year": '2021',
        "venue": 'Journal of Cloud Computing',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['serverless', 'benchmarking', 'performance evaluation'],
        "pdf_link": 'https://journalofcloudcomputing.springeropen.com/articles/10.1186/s13677-021-00253-7',
        "doi": '10.1186/s13677-021-00253-7',
        "source_list": 'paper_list_2',
        "metrics": 'Benchmark frameworks, comparative analysis',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 94,
        "original_id": '',
        "title": 'Serverless Computing: Current Trends and Open Problems – A Comprehensive Survey',
        "authors": 'Hossein Shafiei, Ahmad Khonsari, Payam Mousavi',
        "year": '2022',
        "venue": 'ACM Computing Surveys',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['serverless', 'survey', 'performance'],
        "pdf_link": 'https://arxiv.org/pdf/1911.01296.pdf',
        "doi": '10.1145/3478905',
        "source_list": 'paper_list_2',
        "metrics": 'Field trends and open issues',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 95,
        "original_id": '',
        "title": 'A survey on cold-start latency approaches in serverless computing',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'Computing',
        "category": 'Latency',
        "keywords": ['cold start', 'latency', 'serverless'],
        "pdf_link": 'https://link.springer.com/article/10.1007/s00607-024-01335-5',
        "doi": '10.1007/s00607-024-01335-5',
        "source_list": 'paper_list_2',
        "metrics": 'Comparative latency techniques',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 96,
        "original_id": '',
        "title": 'Low-latency edge-cloud serverless computing with a multi-armed bandit scheduler',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'IEEE Transactions on Cloud Computing',
        "category": 'Latency, Resource Management',
        "keywords": ['latency', 'edge computing', 'scheduling'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10592558/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Minimal end-to-end latency',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 97,
        "original_id": '',
        "title": 'EdgeFaaSBench: Benchmarking edge devices using serverless computing',
        "authors": 'Anonymous',
        "year": '2022',
        "venue": 'IEEE EDGE',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['edge computing', 'benchmark'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/9860334/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Edge device latency/performance',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 98,
        "original_id": '',
        "title": 'BenchFaaS: Benchmarking serverless functions in an edge computing network testbed',
        "authors": 'Anonymous',
        "year": '2022',
        "venue": 'IEEE ICCCN',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['benchmark', 'edge network'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/9877930/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Function execution metrics',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 99,
        "original_id": '',
        "title": 'Performance characterization of data-store event triggers for serverless computing',
        "authors": 'Anonymous',
        "year": '2025',
        "venue": 'IEEE ICDCS',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['event triggers', 'performance'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/11044819/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Trigger latency analysis',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 100,
        "original_id": '',
        "title": 'SeBS-Flow: Benchmarking serverless cloud function workflows',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'ACM SoCC',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['workflows', 'benchmark'],
        "pdf_link": 'https://dl.acm.org/doi/10.1145/3689031.3717465',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Workflow execution times',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 101,
        "original_id": '',
        "title": 'Accelerating serverless computing by harvesting idle resources',
        "authors": 'Anonymous',
        "year": '2022',
        "venue": 'arXiv',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['resource harvesting', 'performance'],
        "pdf_link": 'https://arxiv.org/pdf/2108.12717.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Idle resource utilization',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 102,
        "original_id": '',
        "title": 'Scalable continuous benchmarking on cloud FaaS platforms',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'arXiv',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['continuous benchmarking'],
        "pdf_link": 'https://arxiv.org/pdf/2405.13528.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Real-time performance monitoring',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 103,
        "original_id": '',
        "title": 'Comparison of FaaS performance in private clouds',
        "authors": 'Anonymous',
        "year": '2022',
        "venue": 'SCITEPRESS',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['private cloud', 'FaaS'],
        "pdf_link": 'https://www.scitepress.org/Papers/2022/111167/111167.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Provider performance comparison',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 104,
        "original_id": '',
        "title": 'Evaluating serverless deployment models on AWS Lambda',
        "authors": 'Anonymous',
        "year": '2025',
        "venue": 'SCITEPRESS',
        "category": 'Benchmarking & Evaluation, Cost',
        "keywords": ['AWS Lambda', 'cost', 'performance'],
        "pdf_link": 'https://www.scitepress.org/Papers/2025/132795/132795.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Deployment cost vs. performance',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 105,
        "original_id": '',
        "title": 'Benchmarking serverless computing: performance and usability',
        "authors": 'Anonymous',
        "year": '2022',
        "venue": 'IGI Global',
        "category": 'Benchmarking & Evaluation',
        "keywords": ['usability', 'performance'],
        "pdf_link": 'https://www.igi-global.com/article/benchmarking-serverless-computing/299374',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'User-centric benchmarking',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 106,
        "original_id": '',
        "title": 'Serverless architecture for efficient Monte Carlo MCMC computation',
        "authors": 'Anonymous',
        "year": '2023',
        "venue": 'arXiv',
        "category": 'Resource Management, Performance',
        "keywords": ['MCMC', 'serverless'],
        "pdf_link": 'https://arxiv.org/pdf/2310.04346.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Compute resource utilization',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 107,
        "original_id": '',
        "title": 'Efficiency in the serverless paradigm: reuse & approximation aspects',
        "authors": 'Anonymous',
        "year": '2023',
        "venue": 'Future Generation Computer Systems',
        "category": 'Resource Management',
        "keywords": ['reuse', 'approximation'],
        "pdf_link": 'https://arxiv.org/pdf/2110.06508.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Resource efficiency models',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 108,
        "original_id": '',
        "title": 'Resource management review in serverless computing',
        "authors": 'Anonymous',
        "year": '2023',
        "venue": 'IEEE Transactions on Cloud Computing',
        "category": 'Resource Management',
        "keywords": ['auto-scaling', 'allocation'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10249574/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Scaling strategy analysis',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 109,
        "original_id": '',
        "title": 'Joint resource management & pricing for serverless edge offloading',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'IEEE Transactions on Services Computing',
        "category": 'Resource Management, Cost',
        "keywords": ['pricing', 'edge offloading'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10329995/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Revenue and energy savings',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 110,
        "original_id": '',
        "title": 'ATOM: AI-powered sustainable resource management',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'IEEE Transactions on Cloud Computing',
        "category": 'Resource Management, Energy Consumption',
        "keywords": ['AI', 'sustainability'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10376318/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Energy and CO₂ evaluation',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 111,
        "original_id": '',
        "title": 'On the power consumption of serverless functions: An evaluation',
        "authors": 'Abdulaziz Alhindi, Karim Djemame, Fatemeh Banaie Heravan',
        "year": '2022',
        "venue": 'IEEE Computers in Science & Engineering',
        "category": 'Energy Consumption',
        "keywords": ['power consumption', 'OpenFaaS'],
        "pdf_link": 'https://eprints.whiterose.ac.uk/id/eprint/193714/1/cifs2022-final.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Power usage measurements',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 112,
        "original_id": '',
        "title": 'QoS fairness in serverless functions',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'IEEE Transactions on Services Computing',
        "category": 'Reliability & QoS',
        "keywords": ['QoS', 'fairness'],
        "pdf_link": 'https://ieeexplore.ieee.org/document/10631094/',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'QoE fairness indices',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 113,
        "original_id": '',
        "title": 'Security & privacy edge serverless anomaly detection',
        "authors": 'Anonymous',
        "year": '2023',
        "venue": 'ACM e-Energy Conference',
        "category": 'Security & Privacy',
        "keywords": ['anomaly detection', 'privacy'],
        "pdf_link": 'https://mediatum.ub.tum.de/doc/1638732/1638732.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Detection accuracy and performance',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 114,
        "original_id": '',
        "title": 'Privacy quantification of serverless computing',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'Journal of Cloud Computing',
        "category": 'Security & Privacy',
        "keywords": ['privacy quantification'],
        "pdf_link": 'https://journalofcloudcomputing.springeropen.com/articles/10.1186/s13677-024-00703-y',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Risk assessment models',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 115,
        "original_id": '',
        "title": 'GPU-oriented data transfer for serverless computing',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'arXiv',
        "category": 'Performance, Resource Management',
        "keywords": ['GPU transfer', 'performance'],
        "pdf_link": 'https://arxiv.org/pdf/2411.01830.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Data transfer throughput',
        "abstract": '',
        "notes": ''
    },
    {
        "unified_id": 116,
        "original_id": '',
        "title": 'Caching aided multi-tenant serverless computing',
        "authors": 'Anonymous',
        "year": '2024',
        "venue": 'arXiv',
        "category": 'Performance, Resource Management',
        "keywords": ['caching', 'multi-tenancy'],
        "pdf_link": 'https://arxiv.org/pdf/2408.00957.pdf',
        "doi": '',
        "source_list": 'paper_list_2',
        "metrics": 'Cache hit rate and latency',
        "abstract": '',
        "notes": ''
    },
]

# Enhanced metric keywords for classification
metric_keywords = {
    "Latency": ["latency", "cold start", "response time", "tail latency", "startup time", "delay", "responsiveness", "warm-up", "initialization", "boot time"],
    "Reliability & QoS": ["reliability", "qos", "quality of service", "sla", "slo", "fairness", "availability", "fault tolerance", "consistency", "uptime", "service level", "dependability"],
    "Security & Privacy": ["security", "privacy", "attack", "vulnerability", "authentication", "authorization", "encryption", "threat", "malware", "breach", "confidentiality", "integrity"],
    "Cost": ["cost", "pricing", "revenue", "billing", "economic", "financial", "budget", "expense", "optimization", "savings", "efficiency"],
    "Energy Consumption": ["energy", "power", "co2", "green computing", "carbon", "consumption", "efficiency", "sustainable", "environmental", "electricity", "watt"],
    "Resource Management": ["resource", "scaling", "allocation", "orchestration", "container", "scheduling", "auto-scaling", "provisioning", "utilization", "deployment", "optimization"],
    "Benchmarking & Evaluation": ["benchmark", "evaluation", "suite", "comparison", "framework", "workload", "performance characterization", "testing", "measurement", "analysis", "assessment", "study"]
}

def classify_paper_metrics(paper):
    """Classify a paper across all metrics based on its content"""
    category = str(paper.get('category', '')).lower()
    keywords = str(paper.get('keywords', '')).lower()
    title = str(paper.get('title', '')).lower()
    
    # Combine all text for analysis
    text = f"{category} {keywords} {title}"
    
    classification = {}
    for metric, metric_keywords_list in metric_keywords.items():
        classification[metric] = any(kw in text for kw in metric_keywords_list)
    
    return classification

def get_statistics():
    """Get statistics about the paper collection"""
    total_papers = len(papers)
    
    # Count by source
    source_counts = {}
    for paper in papers:
        source = paper['source_list']
        source_counts[source] = source_counts.get(source, 0) + 1
    
    # Count by year
    year_counts = {}
    for paper in papers:
        year = paper['year']
        if year:
            year_counts[year] = year_counts.get(year, 0) + 1
    
    # Count by category
    category_counts = {}
    for paper in papers:
        category = paper['category']
        if category:
            category_counts[category] = category_counts.get(category, 0) + 1
    
    return {
        'total_papers': total_papers,
        'source_counts': source_counts,
        'year_counts': year_counts,
        'category_counts': category_counts
    }

# Print summary when imported
print(f"✅ Unified Papers Collection: {len(papers)} papers loaded")
print("📚 Import this file using: from all_papers_unified import papers")
print("🔧 Available functions: get_statistics(), classify_paper_metrics(paper)")

if __name__ == "__main__":
    stats = get_statistics()
    print(f"
=== COLLECTION STATISTICS ===")
    print(f"Total papers: {stats['total_papers']}")
    print(f"Source distribution: {stats['source_counts']}")
    years = [y for y in stats['year_counts'].keys() if y]
    if years:
        print(f"Year range: {min(years)} - {max(years)}")
    
    print(f"
Top 10 categories:")
    for cat, count in sorted(stats['category_counts'].items(), key=lambda x: x[1], reverse=True)[:10]:
        print(f"  {cat}: {count} papers")
